import { Montserrat } from 'next/font/google'
import './globals.css'
import Navbar from '@/app/components/Navbar'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Online Shop | ALL DEALS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className='container'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
